### ISSUE TITLE
Bug: In alert

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#118] opened 2021-03-31 17:45 UTC
**Describe the bug**

Clicking on the cross button of alert shows the following error
![image](https://user-images.githubusercontent.com/56021229/113187405-73b57480-9276-11eb-9994-f774bbab694f.png)

Also, this is not responsive for mobile phones.

**Expected behavior**

Everything should work without any error

**Additional context**

By alert I mean:
![image](https://user-images.githubusercontent.com/56021229/113187683-c3943b80-9276-11eb-8e63-f84824187bc8.png)

**Comment by anushri20** [comment] 2021-04-01 04:36
@Namanl2001 Hi, I would like to work on this.

**Comment by Namanl2001** [comment] 2021-04-10 11:52
@anushri20 are you working on this?

**Comment by anushri20** [comment] 2021-04-11 12:45
@Namanl2001 tried to solve the bug but wasn't able to.

**Comment by Namanl2001** [comment] 2021-04-11 13:56
> 
> 
> @Namanl2001 tried to solve the bug but wasn't able to.

Tried discussing with mentors of this project?

**Comment by tend2infinity** [comment] 2021-04-17 21:55
@Namanl2001 I want to work on this issue. I can simply remove the cancel button on the corner to avoid this error. Actually the problem is the modal gets disappeared after a certain period and if we close it before that time then when that period will end the callback will fire and it will try to remove to modal which is actually NOT present at that moment! So, the simple fix would be to remove that cancel button

**Comment by Namanl2001** [comment] 2021-04-17 22:17
Nica catch! 👍  Please go ahead with it.

**Closed** 2021-04-18 12:07 UTC
Labels: GSSOC21, Level1, UIs/ReactJS, help wanted
